import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<section>{children}</section>
				<footer>
					&copy; 2023 My Website. All rights reserved.
					<a href="https://github.com/vercel/next.js/tree/canary/examples/with-typescript">
						Source code
					</a>
					|<a href="https://vercel.com">Powered by Vercel</a>
				</footer>
			</body>
		</html>
	);
}
