import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { type ReactNode } from "react";
import { ActiveLink } from "@/ui/atoms/ActiveLink";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang="pl">
			<body className={inter.className}>
				<nav className="sticky top-0 flex h-16 items-center justify-center bg-zinc-200 bg-opacity-60 backdrop-blur-xl">
					<ul className="flex gap-5">
						<li>
							<ActiveLink href="/">Homepage</ActiveLink>
						</li>
						<li>
							<ActiveLink href="/products" exact={false}>
								Produkty
							</ActiveLink>
						</li>
					</ul>
				</nav>
				<section className="mt-5 flex justify-center">{children}</section>
				<footer>
					&copy; 2023 My Website. All rights reserved.
					<a href="https://github.com/vercel/next.js/tree/canary/examples/with-typescript">
						Source code
					</a>
					|<a href="https://vercel.com">Powered by Vercel</a>
				</footer>
			</body>
		</html>
	);
}
